language: python
python: 2.7
env:
  - PLONE_VERSION=5.1
#  - PLONE_VERSION=5.1 QA=true
#  - PLONE_VERSION=5.2
install:
  - sed -ie "s#travis-5.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/code-analysis && bin/test
after_success: test $QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
